name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 5 * * 0'

env:
  REGISTRY: 'rg.fr-par.scw.cloud'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker login -u anyuser -p ${{ secrets.SCALEWAY_TOKEN }} $REGISTRY
        docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ secrets.SCALEWAY_REGUSER }}/syslog-cloudwatch-bridge:latest
        docker push ${{ env.REGISTRY }}/${{ secrets.SCALEWAY_REGUSER }}/syslog-cloudwatch-bridge:latest
